---

language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_deploy:
  - script/generate-zip
deploy:
  provider: releases
  api_key: "$RELEASES_TOKEN"
  file: "metacpan.lbaction.zip"
  skip_cleanup: true
  on:
    tags: true
